// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FrontendDispatcher(arg1:string,arg2:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function SendMessageFromFrontend(arg1:string):Promise<void>;

export function StartWebSocketServer():Promise<void>;
