// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SendMessageFromFrontend(arg1) {
  return window['go']['main']['App']['SendMessageFromFrontend'](arg1);
}

export function StartWebSocketServer() {
  return window['go']['main']['App']['StartWebSocketServer']();
}
